services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: ${PHP_CONTAINER_NAME}
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE}
      - PHP_IDE_CONFIG=serverName=php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - siroko-network
    depends_on:
      - mysql
      - redis
      - elasticsearch

  nginx:
    image: nginx:alpine
    container_name: ${NGINX_CONTAINER_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - siroko-network

  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - siroko-network

  redis:
    image: redis:alpine
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - siroko-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: ${ELASTIC_CONTAINER_NAME}
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "${ELASTIC_PORT1}:9200"
      - "${ELASTIC_PORT2}:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - siroko-network

volumes:
  mysql_data:
  elasticsearch_data:

networks:
  siroko-network:
    driver: bridge
