parameters:
    user.permissions_map:
        ROLE_USER_MANAGE:    ['LET_USER_READ', 'LET_USER_WRITE']
        ROLE_PRODUCT_MANAGE: ['LET_PRODUCT_READ','LET_PRODUCT_WRITE']
        ROLE_CART_MANAGE:    ['LET_CART_READ','LET_CART_WRITE']
        ROLE_CUSTOMER:       ['LET_OWN_CART_READ','LET_OWN_CART_WRITE','LET_PRODUCT_READ']
        ROLE_USER:           ['LET_PRODUCT_READ']
