gesdinet_jwt_refresh_token:
    refresh_token_class: Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken
    ttl: 2592000 # 30 días
    token_parameter_name: refresh_token
    user_identity_field: email
    single_use: true
