nelmio_cors:
    defaults:
        allow_credentials: false
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
