# config/packages/security.yaml
imports:
    - { resource: '@UserBundle/Resources/config/security_roles.yaml' }

security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: UserBundle\Infrastructure\Persistence\Mysql\UserDoctrineEntity
                property: userEmail
        users_in_memory:
            memory: null

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/users/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/users/login
                username_path: email
                password_path: password

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        # Public routes
        - { path: ^/api/users/register, roles: PUBLIC_ACCESS, methods: [ POST ] }
        - { path: ^/api/users/login, roles: PUBLIC_ACCESS, methods: [ POST ] }
        - { path: ^/api/users/token/refresh, roles: PUBLIC_ACCESS, methods: [ POST ] }
        - { path: ^/api/users/auth/google$, roles: PUBLIC_ACCESS }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
