controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_bundle:
    resource: ../siroko-bundles/ProductBundle/Resources/config/routes.yaml

cart_bundle:
    resource: ../siroko-bundles/CartBundle/Resources/config/routes.yaml
